macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  name: Test
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  test_script:
    - cargo test -- --test-threads 1
  env:
    PATH: "$PATH:$HOME/.cargo/bin"

task:
  name: Lint
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  rustfmt_script:
    - cargo fmt --check
  clippy_script:
    - cargo clippy --all-targets --all-features -- -D warnings
  env:
    PATH: "$PATH:$HOME/.cargo/bin"
