macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  name: Test
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  test_script:
    - cargo test -- --test-threads 1
  env:
    PATH: "$PATH:$HOME/.cargo/bin"

task:
  name: Lint
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  rustfmt_script:
    - cargo fmt --check
  clippy_script:
    - cargo clippy --all-targets --all-features -- -D warnings
  env:
    PATH: "$PATH:$HOME/.cargo/bin"

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Test
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  install_cargo_release_script:
    - cargo install --version 0.24.11 cargo-release
  bump_version_script:
    - cargo release version --execute --workspace --no-confirm $CIRRUS_TAG
  release_script:
    - cargo release --execute --workspace --no-tag --no-push
  env:
    PATH: "$PATH:$HOME/.cargo/bin"
    CARGO_REGISTRY_TOKEN: ENCRYPTED[34d8493f2be8724f994ca87ab9f3c9bfe419fa36d9dcb612e68cee795d29e4e73867b6ebc53c27e727358c410ec3bf73]
