macos_instance:
  image: ghcr.io/cirruslabs/macos-runner:tahoe

task:
  use_compute_credits: true
  alias: Test

  matrix:
    - name: Test on macOS Sequoia
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sequoia
    - name: Test on macOS Tahoe
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:tahoe

  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  test_script:
    - cargo test -- --test-threads 1

  env:
    PATH: "$PATH:$HOME/.cargo/bin"

task:
  name: Lint
  use_compute_credits: true

  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  rustfmt_script:
    - cargo fmt --check
  clippy_script:
    - cargo clippy --all-targets --all-features -- -D warnings

  env:
    PATH: "$PATH:$HOME/.cargo/bin"

task:
  name: Release
  use_compute_credits: true
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Test

  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  release_script:
    - cargo publish -p vmnet-derive || true
    - cargo publish

  env:
    PATH: "$PATH:$HOME/.cargo/bin"
    CARGO_REGISTRY_TOKEN: ENCRYPTED[5ea2a3f24d40ec22276e973c70d353ec7f5e817bf7921d7e07c75e5124a669a076a297c42837d06be4d4130d88c95026]
